### ISSUE TITLE
Create-DesktopIcon Icon Issue

### ISSUE THREAD

**Issue by Wildfowl4777** [JayRHa/Intune-Scripts#3]
Hey, I am having an issue where the script does not pull the icon into the shortcut. Although this is not specific to your script, I am not sure how to search for it.

When I go to the properties of the icon, and hit Change Icon, it says "Windows can't find the file https://my.url/images/favicon.ico", however if I go to that URL it is publicly available and goes right to the image. This image is also an ico, not one that points to a png or jpg.

Thank you for your help and your scripts, they are very helpful.

**Comment by JayRHa** [comment]
Is it better for you if I update my blog/script that the icon is part of the app and that it is not necessary to store it on a web storage?

**Comment by Wildfowl4777** [comment]
When creating the shortcut link through the script it will not pull the icon from the URL. Is there a different way to add the custom .ico to the shortcut link?

**Comment by JayRHa** [comment]
Hi Wildfowl4777, I changed the script that the icon will be downloaded from the URL and makes it more reliable.
