### ISSUE TITLE
Script is too large for Intune

### ISSUE THREAD

**Issue by chris-fp** [JayRHa/Intune-Scripts#4]
When I try to upload the script to Intune, it tells me that the script must be between 1 and 200000 bytes long and it appears that the deploy script is 209,637 bytes long

**Comment by JayRHa** [comment]
Hi chris, thank you for opening a bug. Which script did you mean?

**Comment by chris-fp** [comment]
ignore me - made a mad mistake....gonna have to run and hide of embarrassment :(
